### ISSUE TITLE
libgcc_s_seh-1.dll is missing in production(Windows)

### ISSUE THREAD

**Issue by HDK101** [andrew-r-king/sfml-vscode-boilerplate#15]
libgcc_s_seh-1.dll is missing in build folder, therefore, windows builds will not run.

**Comment by andrew-r-king** [comment]
Looks like you're using the 64-bit version of GCC. go into env/windows.all.mk and under PRODUCTION_DEPENDENCIES, change:

```
$(_MINGW)/libgcc_s_dw2-1.dll
```
to
```
$(_MINGW)/libgcc_s_seh-1.dll
```

**Comment by HDK101** [comment]
Ah ok, thanks!
