### ISSUE TITLE
C++17 filesystem

### ISSUE THREAD

**Issue by RedRobin84** [andrew-r-king/sfml-vscode-boilerplate#16]
Hello Andrew!

First, thank you for this perfectional cross-platform build!

I successfully installed your project, but now I have a problem with implementing some c++17 features. Currently filesystem. Even I have c+17 standard setting (tried even c++20) C++ extension on VS code cannot find the library.
It runs only as 
`#include experimental/filesystem> `

That's early c++17 or less ... so I am wondering if that's project issue or C++ for VS code extension issue.

**Comment by RedRobin84** [comment]
Update: even experimental/filesystem is not working. Linker is not able to find it.

**Comment by andrew-r-king** [comment]
The short answer is that it depends on the GCC version you're using. GCC 7.3.0 (recommended in the boilerplate for its easy install on windows) uses the experimental header, while GCC 8+ (which can be installed on windows through MSYS2) does not.

Both require an additional lib to be linked for the filesystem import (in env/.all.mk for instance). I'm not sure yet if that changed in 9.x:
```make
LINK_LIBRARIES : =\
    stdc++fs
```

To ensure it compiles with 7.x & 8+, You just need to use a macro. The actual filesystem prefix is long, so I'd recommend something like this in the source file you use it in (or throw it in the PCH):
```cpp
// std::filesystem
#if __GNUC__ >= 8
	#include <filesystem>
	namespace fs = std::filesystem;
#else
	#include <experimental/filesystem>
	namespace fs = std::experimental::filesystem::v1;
#endif
```

and then as a quick test:
```cpp
if (fs::exists("content/stub.txt"))
{
	std::cout << "Yo" << std::endl;
}
```

**Comment by RedRobin84** [comment]
It's working perfectly now. Thank you for your clear explanation!
