### ISSUE TITLE
Using non pre-built or non header-only libraries

### ISSUE THREAD

**Issue by dmoa** [andrew-r-king/sfml-vscode-boilerplate#17]
If I were to use non pre-built or non header-only libraries, how would you do it?

**Comment by andrew-r-king** [comment]
If you don't want to include the library in your project:

- Add the include path (mylib/include) to the `INCLUDE_DIRS` variable (in the respective `env/*.mk` file)
- Add the lib path (mylib/lib) to the `LIB_DIRS` variable
- Add the lib name to `LINK_LIBRARIES`. This is generally a `lib(name).a` file, it it can also be `(name).lib`
- Also add the include path to ".vscode/c_cpp_properties.json". This tells intellisense where to look.

Folders might vary depending on the library.

If you want to include the library in your project, it's a similar process:
(I have an XInput.lib and a single XInput.h file for instance)

- Make a folder in the local lib/ for it (lib/XInput/)
- Add the lib name to `LINK_LIBRARIES`

The lib folder is already used as a search directory, so you don't need to do anything else.

**Comment by dmoa** [comment]
Will try thank you!

**Comment by andrew-r-king** [comment]
Sorry I misread this when I first commented. That was for prebuilt libaries. For non-prebuilt libraries:

Build the library with the same compiler that you use with this. This step can vary - if the library is compatible with cmake, just use cmake (just as you would in building SFML). You could make a bash script to simplify this. If you review the MSYS2 instructions at the bottom of the boilerplate readme, you'll kind of get a sense of the process. This is the library build script I wrote for SFML, although keep it mind it also builds the examples, docs & static libraries:

https://gist.github.com/andrew-r-king/5f8ea0eda064cbfb33f4f5d373011e0b

You can pretty much swap out the compiler or version of mingw you're using, make a path for MY_LIB & go from there. 

Once built, it's similar to the above directions. You can choose to include include it directly in the project or in another directory somewhere.

If you're making your own library (a game engine framework for example), this boilerplate does support multiple build targets, (so you can build both the dll and a sample project in one go), but I still have to document it and make improvements, in addition to improving the documentation as a whole (wiki style).
