### ISSUE TITLE
Running C/C++ CI action build on Github

### ISSUE THREAD

**Issue by BenjaminMichaelis** [andrew-r-king/sfml-vscode-boilerplate#22]
Not sure if I am doing something very obvious wrong or not including something but I keep getting this error when I try to trigger a workflow build on Github. Any ideas?
```
Run make
tput: No value for $TERM and no -T specified
make[1]: *** [bin/Release/obj/PCH.hpp.gch] Error 2
Makefile:315: recipe for target 'bin/Release/obj/PCH.hpp.gch' failed
make: *** [all] Error 2
Makefile:259: recipe for target 'all' failed
Error: Process completed with exit code 2.
```

**Comment by BenjaminMichaelis** [comment]
Got around the Makefile:259 error by running `make makebuild` instead of just `make`
```
Run make makebuild
tput: No value for $TERM and no -T specified
Makefile:315: recipe for target 'bin/Release/obj/PCH.hpp.gch' failed
make: *** [bin/Release/obj/PCH.hpp.gch] Error 2
Error: Process completed with exit code 2.
```

**Comment by andrew-r-king** [comment]
The fix for this is tricky but this should get it kind of working:
https://github.com/andrew-r-king/sfml-vscode-boilerplate/commit/ae2b3479569e1ff8bbaf5a63f85ffb66e5cbf9c2

In the Windows settings, you basically have to write the actions so that that the build script (and make) run inside of MSYS2, but there might be other hurdles.

Admittedly this wasn't tested in Github actions previously. I've been working on a new replacement build system that does have CI support. It's basically this, but a lot more robust, and written in C++. It does do the CMake thing of generating makefiles, but it's a lot cleaner. It's faster than this project, but not quite as fast as CMake yet (especially in CI). The build can be managed from a single json file.

**Comment by BenjaminMichaelis** [comment]
Thanks for taking a look at this!
I tried this update, and it looks like I am still getting the same error in both of my build types (I am trying both a `make makebuild` command, and a `bash build.sh build` which could both be wrong for actions but wanted to try two routes). While there are different errors for both, the common error between both is `tput: No value for $TERM and no -T specified`

**Comment by andrew-r-king** [comment]
Ah right. I missed the tput part before. That was another thing I had to change in my new build system. Pushed up some new changes that should fix it:
https://github.com/andrew-r-king/sfml-vscode-boilerplate/commit/5a8bc9299675cc95d4dda8355d57a93cea8c9946

**Comment by BenjaminMichaelis** [comment]
Getting closer, on my make build I have this include error now, do the .hpps have to be included in the repo because it's hosted on github?
```
Run make makebuild
   src/PCH.hpp
src/PCH.hpp:11:10: fatal error: SFML/Audio.hpp: No such file or directory
 #include <SFML/Audio.hpp>
          ^~~~~~~~~~~~~~~~
compilation terminated.
Makefile:316: recipe for target 'bin/Release/obj/PCH.hpp.gch' failed
make: *** [bin/Release/obj/PCH.hpp.gch] Error 1
Error: Process completed with exit code 2.
```
On my windows bash build I have this error now;
```
Run bash build.sh build
build.sh PATH=/c/SFML-2.5.1/bin:/c/mingw32/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
⬤  Build: Release (target: sfmlFlashcards.exe)
build.sh: line 100: make: command not found
✘  Failed!
   Review the compile errors above.
Error: Process completed with exit code 1.
```

**Comment by andrew-r-king** [comment]
If you're still talking about CI server and not locally, you need to build SFML (or fetch the 2.51. build with curl) in your github actions, and make sure the search paths are correct in the CI server. I'd make a separate shell script that defines the PATH correctly. I can tell you it will not be /c/SFML-2.5.1/bin on the server.

**Comment by BenjaminMichaelis** [comment]
Yes, thank you for that reminder, after installing the Linux dependencies, it seems to be building!
Will work on a solution for Windows at some point.
Thank you!
