### ISSUE TITLE
Using libraries

### ISSUE THREAD

**Issue by jamestoh-leos** [andrew-r-king/sfml-vscode-boilerplate#23]
So i followed the tutorial for adding libraries to the lib folder.
I have a folder in lib which contains
Tolk \
  Tolk.h
  Tolk.lib
I also added it in env/windows.all.mk
LINK_LIBRARIES := \
	$(LINK_LIBRARIES) \
	stdc++fs \
	Tolk \
	gdi32
When i try to build it gave me this error:
⬤ Build & Run: Release (target: demo2.exe) ⇛ Linking: bin/Release/demo2.exe C:/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lTolk collect2.exe: error: ld returned 1 exit status mingw32-make[1]: *** [Makefile:350: bin/Release/demo2.exe] Error 1 mingw32-make: *** [Makefile:260: all] Error 2 ✘ Failed! Review the compile errors above. The terminal process "C:\Program Files\Git\bin\bash.exe '-c', 'bash ./build.sh buildrun Release vscode'" terminated with exit code: 1. Terminal will be reused by tasks, press any key to close it.

**Comment by andrew-r-king** [comment]
Try adding the subfolder to LIB_DIRS:
```
LIB_DIRS := \
    Tolk
```

**Comment by jamestoh-leos** [comment]
I did it and it gave me:
env/windows.all.mk:9: *** recipe commences before first target. Stop.
 
✘ Failed!

**Comment by jamestoh-leos** [comment]
Yes it seems if i add the Folder name to the file i get:
env/windows.all.mk:9: *** recipe commences before first target. Stop.
Here is the segment:
LIB_DIRS := \
	$(_SFML)/lib
	Tolk

I call the .h file of the folder via:
#include <Tolk/Tolk.h>

**Comment by andrew-r-king** [comment]
It's make syntax so you have to have backslashes in each line that isn't the last line:

```
LIB_DIRS := \
    $(_SFML)/lib \
    Tolk
```

**Comment by jamestoh-leos** [comment]
So i got the thing to load i think. Do i have to declare the location or how do i include the required DLL for that lib?

**Comment by jamestoh-leos** [comment]
It seems it is not linking the lib in that folder to the main exe, cause it is still not able to see the functions that is declared in the .h file.

**Comment by andrew-r-king** [comment]
Oh I think it's actually:
```
LIB_DIRS := \
    $(LIB_DIRS ) \
    $(_SFML)/lib \
    lib/Tolk
```

If the library has been compiled separately (has a lib**.a file):
```
LINK_LIBRARIES: \
    $(LINK_LIBRARIES) \
    Tolk
```

The paths are relative to the project root. Also, if the library has sources to compile, you have to include the sources in the src folder (```src/vendor/mylib``` or something like that) and they will just get picked up, but you have to deal with the compiler warnings/errors you might get.  If the library is header-only, or precompiled, it can be included in the the lib folder. The lib directory is implicitly included, but only at the root level, so if you have ```lib/mylib/mylib_header.hpp```, The include would be

```
#include <mylib/mylib_header.hpp>
```

If you want:
```
#include <mylib_header.hpp>
```

You just need to add ```lib/mylib``` to LIB_DIRS.

**Comment by jamestoh-leos** [comment]
Oh cool. It works now, thanks
