### ISSUE TITLE
SFML/Audio.hpp not found (MacOS)

### ISSUE THREAD

**Issue by Edersteiner** [andrew-r-king/sfml-vscode-boilerplate#24]
When I try to build and run I get this:

   src/PCH.hpp
src/PCH.hpp:11:10: fatal error: 'SFML/Audio.hpp' file not found
#include <SFML/Audio.hpp>
         ^~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [bin/Debug/obj/PCH.hpp.pch] Error 1
make: *** [all] Error 2

✘  Failed!
   Review the compile errors above.
   

I'm on MacOS 11 Big Sur and I'm using an M1 MacBook Air.

**Comment by StephaneBranly** [comment]
Check that you have correctly installed SMFL on your mac. You should have this header (`Audio.hpp`) file in `/usr/local/include/SFML`. 

If not, follow the instructions here : [https://www.sfml-dev.org/tutorials/2.5/start-osx.php#installing-sfml](https://www.sfml-dev.org/tutorials/2.5/start-osx.php#installing-sfml)

**Comment by andrew-r-king** [comment]
I also just want to point out that if you're using a M1 Mac right now, I believe you'll need to build SFML from source (master branch).
