### ISSUE TITLE
bin/Debug/sfml-vscode-boilerplateld: library not found for -lsfml-graphics

### ISSUE THREAD

**Issue by wevbute** [andrew-r-king/sfml-vscode-boilerplate#26]
My system 
- m1 mac
- big sur 

<img width="760" alt="Screen Shot 2021-04-11 at 10 53 15 AM" src="https://user-images.githubusercontent.com/72121955/114289597-3c379b00-9ab4-11eb-954c-cc86876d0551.png">
<img width="361" alt="Screen Shot 2021-04-11 at 10 54 31 AM" src="https://user-images.githubusercontent.com/72121955/114289610-596c6980-9ab4-11eb-8a1e-9503316ec064.png">

i downloaded SFML-2.5.1-macos-clang and copied include/SFML and pasted into my /usr/local/include

* i removed SFML from my /usr/loca/include and tried brew install sfml and that same error pops up
<img width="568" alt="Screen Shot 2021-04-11 at 10 59 25 AM" src="https://user-images.githubusercontent.com/72121955/114289705-fdeeab80-9ab4-11eb-8d76-4aa045a266be.png">

**Comment by andrew-r-king** [comment]
You have to build SFML from source on M1 arch right now (the precompiled 2.5.1 version won't work)
