### ISSUE TITLE
Building production on macOS

### ISSUE THREAD

**Issue by nathandaven** [andrew-r-king/sfml-vscode-boilerplate#27]
Building for debug and release work just fine, but I'm getting this error even when I try to run production build from my own terminal:

```
❯ ./build.sh buildprod Release vscode    
⬤  Production Build: Release (target: SFMLGame)

   Target is up to date.

   Creating the MacOS application bundle...

/Users/nathandaven/DevLocal/SFMLGame/env/osx/sfml.png
  /Users/nathandaven/DevLocal/SFMLGame/build/SFML Boilerplate.app/Contents/Resources/sfml.icns

   Adding dynamic libraries & project dependencies...

printf: missing format character
➦  Copying "content" to "/Users/nathandaven/DevLocal/SFMLGame/build/SFMLmake: *** [makeproduction] Error 1

✘  Failed!
   Review the compile errors above.
```

Edit: It does produce a .app under /build that runs, but it still gives me this error in the terminal and no .dmg, not sure why.

**Comment by andrew-r-king** [comment]
Ah, yeah that got borked somehow. I just pushed up some changes to the Makefile that should fix them.

**Comment by nathandaven** [comment]
Works great! Thanks for the quick fix, will close this now
