### ISSUE TITLE
Help error when setting up.

### ISSUE THREAD

**Issue by Spit-Fyre** [andrew-r-king/sfml-vscode-boilerplate#28]
Hi Im quite inexperienced and need some help. The error I get is:

Variable ${config:terminal.integrated.env.windows.Path} can not be resolved because setting 'terminal.integrated.env.windows.Path' not found.

Is their anything I can do? I tried to follow the instructions as best I could thanks.

**Comment by andrew-r-king** [comment]
Sounds like you removed these from settings.json:

```json
"terminal.integrated.env.windows": {
		"Path": "C:/mingw32/bin;C:/SFML-2.5.1/bin"
	},
	"terminal.integrated.env.linux": {
		"PATH": "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
	},
	"terminal.integrated.env.osx": {
		"PATH": "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
	},
```

You can either add them back in, or remove the references to them in launch.json and tasks.json

**Comment by Spit-Fyre** [comment]
Im a bit lost here but I seemed to actually start the myproject folder under a workspace in a different folder and that messed with it a bit. I got it working thanks, although I know its setup atm I'm unsure where to go from here.

**Comment by andrew-r-king** [comment]
Yeah, I'm not sure what you're asking now or trying to do. You could always give CMake a try if that would work better for you.

**Comment by Spit-Fyre** [comment]
Thanks sorry for all the confusion.
