### ISSUE TITLE
How To Include MACOSX Frameworks?

### ISSUE THREAD

**Issue by StevenMartin1** [andrew-r-king/sfml-vscode-boilerplate#29]
Please excuse my ignorace, I'm quite new to this but have manged to get started with SFML using your template which has been working fantastically!

I've been trying to also make use of the RtMidi library found here: https://www.music.mcgill.ca/~gary/rtmidi/

I need to include the 'the appropriate preprocessor definition and libraries' (apparently for Mac OSX something like: **g++ -Wall -D__MACOSX_CORE__ -o midiprobe midiprobe.cpp RtMidi.cpp -framework CoreMIDI -framework CoreAudio -framework CoreFoundation**) but I'm not sure where I should be entering them in the template?

Would you mind guiding me as to where they should go please?

**Comment by andrew-r-king** [comment]
Go into env/osx.all.mk line 16 (MACOS_FRAMEWORKS) and add them there like so:

```make
MACOS_FRAMEWORKS := \
    CoreMIDI \
    CoreAudio \
    CoreFoundation
```

also, edit MACOS_FRAMEWORK_PATHS if needed:

```make
MACOS_FRAMEWORK_PATHS := \
    (custom path) \
    /Library/Frameworks
```

The define would go under "BUILD_MACROS" (should have just called that BUILD_DEFINES or something)

```make
BUILD_MACROS := \
    __MACOSX_CORE__
```

I think those changes should work...

**Comment by StevenMartin1** [comment]
Huge thanks for that! 

Where about's would this go? Also in the osx.all.mk file? 

```
BUILD_MACROS := \
    __MACOSX_CORE__
```

Is there a way to check that those includes have done the job?

For that file I have:

```
CC := clang++
CFLAGS := $(CFLAGS:-s=)

LIB_DIRS := \
	/usr/local/lib

INCLUDE_DIRS := \
	/usr/local/include

BUILD_MACROS := \
    __MACOSX_CORE__

BUILD_FLAGS :=

MACOS_FRAMEWORK_PATHS := \
    /System/Library/Frameworks \
	/system/Library/Frameworks \
    /Library/Frameworks

# Name, no extension (eg. CoreFoundation, ogg)
MACOS_FRAMEWORKS := \
    CoreMIDI \
    CoreAudio \
    CoreFoundation

# Icon .png
PRODUCTION_MACOS_ICON := sfml

PRODUCTION_DEPENDENCIES := \
	$(PRODUCTION_DEPENDENCIES)

PRODUCTION_MACOS_BUNDLE_DEVELOPER := developer
PRODUCTION_MACOS_BUNDLE_DISPLAY_NAME := SFML Boilerplate
PRODUCTION_MACOS_BUNDLE_NAME := SFML Boilerplate
PRODUCTION_MACOS_MAKE_DMG := true
PRODUCTION_MACOS_BACKGROUND := dmg-background

PRODUCTION_MACOS_DYLIBS := \
	/usr/local/lib/libsfml-graphics.2.5 \
	/usr/local/lib/libsfml-audio.2.5 \
	/usr/local/lib/libsfml-network.2.5 \
	/usr/local/lib/libsfml-window.2.5 \
	/usr/local/lib/libsfml-system.2.5

# Path, no extension (eg. /Library/Frameworks/ogg)
PRODUCTION_MACOS_FRAMEWORKS :=

```

But when I run this code for the RtMidi:
```

#include "RtMidi.h"
int main()
{
	try
	{
		RtMidiIn midiin;
	}
	catch (RtMidiError& error)
	{
		// Handle the exception here
		error.printMessage();
	}
	return 0;
}
```
I get: 

`MidiInDummy: This class provides no functionality.`

Which, speaking to others online, apparently means that I've not included those frameworks and the macro. As it should be telling me it's using the MidiInCore (for Mac OSX)

I fully appreciate you're not able to offer support for RtMidi, but when other people tell me to include things I'm quite lost in your template as to where to put them!

**Comment by andrew-r-king** [comment]
Yes that's correct. This is the heirarchy of how those env files are read:

```
./build.sh: Contains the build scripts that tasks.json calls

./env/.all.mk: All platforms & builds
./env/.debug.mk: All platforms, Debug build
./env/.release.mk: All platforms, Release build

./env/linux.all.mk: Linux, All builds
./env/linux.debug.mk: Linux, Debug build
./env/linux.release.mk: Linux, Release build

./env/osx.all.mk: MacOS, All builds
./env/osx.debug.mk: MacOS, Debug build
./env/osx.release.mk: MacOS, Release build

./env/rpi.release.mk: Linux (Raspberry Pi), Release build

./env/windows.all.mk: Windows, All builds
./env/windows.debug.mk: Windows, Debug build
./env/windows.release.mk: Windows, Release build
```

I've never used RtMidiIn, so I can't say how it's supposed to be used (read their docs), but it seems like it's doing what you've told it to do. You are initializing an instance of RtMidiIn, and not doing anything with it, so presumably when it goes out of scope, it throws the error (to your error handler) and prints "MidiInDummy: This class provides no functionality."

**Comment by StevenMartin1** [comment]
Okay, thanks. 

On this URL: https://people.carleton.edu/~jellinge/cs312_w2020/week6_2.html

There's a section that mentions this issue:

```
The missing compile information is highlighted in red. In CMakeLists.txt change this

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17 -Wall ")
to this (double underscore prefix and suffix to __MACOSX_CORE__)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17 -Wall -D __MACOSX_CORE__ ")
Append the necessary framework libraries to the end of CMakeLists.txt

# target_link_libraries must come after add_executable
target_link_libraries(${APPNAME} "-framework CoreMIDI")
target_link_libraries(${APPNAME} "-framework CoreAudio")
target_link_libraries(${APPNAME} "-framework CoreFoundation")

```

If you think based on the above I'm all set up correctly then you may as well close the issue as it's very much a 'Me' problem and not an issue with your template. I just figured I'd come to the creator in case I was missing anything obvious. 

Thanks anyway! And thanks again for the template as it's been great.

**Comment by andrew-r-king** [comment]
If you're unsure about the library's build, maybe CMake would be a better choice here? I'm not sure what you're missing otherwise.
