### ISSUE TITLE
Make for Git bash is needed 

### ISSUE THREAD

**Issue by fahlmant** [andrew-r-king/sfml-vscode-boilerplate#3]
Following the README, the only thing missing was listing a requirement for `make`. Using Git bash, I had to follow the instructions here to get the build.sh to work properly: https://gist.github.com/evanwill/0207876c3243bbb6863e65ec5dc3f058

This requirement should be called out in the instructions.

**Comment by andrew-r-king** [comment]
make is included in mingw32 (mingw32-make.exe), and the script also handles the path. How were you trying to run the script? I'm confused as to how you got to that conclusion.

**Comment by fahlmant** [comment]
The mingw linked in the README didn't have it installed for me. Not sure why

**Comment by fahlmant** [comment]
For some reason the makefile was not finding `mingw32-make` as `make` when running the build commands.
