### ISSUE TITLE
Hey andrew your tutorials was great i followed each every part of instructions properly it suceeded but then this showed up

### ISSUE THREAD

**Issue by Akashkuthe** [andrew-r-king/sfml-vscode-boilerplate#6]
===== Build Succeeded: Launching bin/Debug/stars.exe ======
./build.sh: line 125: bin/Debug/stars.exe: No such file or directory

Terminal will be reused by tasks, press any key to close it.

**Comment by andrew-r-king** [comment]
Hmmm... The name of the build target (stars.exe) is taken from the root/workspace folder name, so if it's "stars", it'll be looking for stars.exe. Even if you changed the folder name, it should still rebuild the exe with the new name before trying to run it. I'm not sure what you did differently. Does Release do the same thing?


"Terminal will be reused by tasks, press any key to close it." just tells you the terminal process itself finished. It's set in tasks.json under:

```json
{
    "presentation": {
        "showReuseMessage": true
    },
}
```

**Comment by Akashkuthe** [comment]
yes,release give me same result!can you tell me what is was system environment variable path for this setup
i think there may be some mistake of mine.
C:\Program Files\Git\bin\bash.exe
C:\mingw32\bin\gcc.exe..........this is my path correct me if i am wrong

**Comment by Akashkuthe** [comment]
Hey, Andrew, I know what's wrong I am working on 32-bit windows system and the MinGW compiler you have mentioned in the description is not a valid  win32 application,
therefore can you suggest another version of MinGW compiler with some configuration and works on the win32 system, I will be grateful for your suggestion.

**Comment by andrew-r-king** [comment]
The one I picked is already 32-bit (i686). The paths you have are correct. I'm more confused at how it could build and claim the exe doesn't exist. Do a fresh clone of the repo, rebuild and send me the whole output.

**Comment by andrew-r-king** [comment]
Akashkuthe, are you still having this issue?
